- .github/workflows/release.yml
- chain/Earthfile
- chain/Makefile
* Multiplatform release
* Windows exe name fix
* Fix version issue
* Earthfile version fix
* Test one binary
* zip command fix
* Fix comments
Co-authored-by: ba1ciu <jakub@empower.eco>
> Multiplatform release (#1)

- chain/app/app.go
> Added group module

- chain/scripts/test/smoke_plastic_credit.sh
- chain/x/plasticcredit/keeper/msg_server_test.go
- chain/x/plasticcredit/keeper/project.go
https://github.com/EmpowerPlastic/empowerchain/issues/402
> Allow approving rejected projects

- chain/tests/e2e/plasticcredit/e2e_test.go
- chain/tests/e2e/plasticcredit/tx_test.go
- chain/x/plasticcredit/keeper/project.go
work in progress for create project CLI smoketests, keeping in draft
> e2e tests for project

- frontend/package-lock.json
- frontend/proof-of-existence/package.json
I linked ts-client to Lerna packages.
> ts-client added to lerna package

- cosmwasm/contracts/plastic-credit-marketplace/src/query.rs
> Added test for the already existing query all listings

- chain/tests/e2e/e2e_base.go
- chain/tests/e2e/marketplace/cancel_listing_test.go
- chain/tests/e2e/marketplace/e2e_test.go
- cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
- cosmwasm/contracts/plastic-credit-marketplace/src/msg.rs
implementation for [cancel listing](https://github.com/EmpowerPlastic/empowerchain/issues/556)
> added cancel listing and tests

- chain/Earthfile
- testnets/emp-devnet-1/Earthfile
- testnets/emp-devnet-1/genesis.json
IBC conformance tests are going to fail if we change the genesis state and it's pretty bad idea to have to change a base genesis.json for devnet in a remote bucket..
> devnet genesis in repo

- chain/Earthfile
Wasn't working with `~`, but didn't throw errors -_-
> Devnet genesis fix

- docs/.vitepress/config.js
- docs/validators/cosmovisor-setup.md
- docs/validators/full-node-setup.md
- docs/validators/validator-setup.md
This PR is still a work in progress, so I've marked it as a draft PR for now. I will continue working on this throughout the week/weekend to get it cleaned up and add some of the TODO sections, but I wanted to start getting feedback on it now in case there are large aspects that the team would like changed. Some links to the Empowerchain repo are assumed to exist once the testnet is live/preparing to go live, but can be modified as needed to point to their proper location.
> Add initial validator documentation

- testnets/circulus-1/gentx/gentx-RHINO.json
> Add RHINO gentx

- indexer/package.json
- indexer/project.yaml
- indexer/scripts/build-with-env.sh
- indexer/src/mappings/mappingHandlers.ts
Haxxy, but better than forking again imo 🤷🏻
> Indexer env build and clean up

- docs/testnet/resources.md
discord: konsortech#1673
website: https://konsortech.xyz
> Add KonsorTech resources.md

- frontend/marketplace/src/pages/AuctionPage.vue
This is the fix for undifined issue -https://app.rollbar.com/a/Empower/fix/item/marketplace/26?utm_campaign=new_item_message&utm_medium=slack&utm_source=rollbar-notification#detail
> undefined issue fix

- frontend/marketplace/src/components/CreditTabContent.vue
- frontend/marketplace/src/pages/AuctionDetails.vue
I ended up using `refetch`, but there's a thing called `polling` in Apollo client, which would be a better fit for this. Unfortunatelly, I didn't manage to get it working with. If you want you can try using it @PiranavanShanmugavadivelu
https://www.apollographql.com/docs/react/data/queries/#polling
> refresh auction balance and my credit balance

- frontend/marketplace/src/components/BuyCredits.vue
- frontend/marketplace/src/pages/AuctionDetails.vue
1.  Disabled buy credit button for invalid input
2.  Show the relevant error in toast
3. UI and responsive fixes
4. `saleDate `added to the `Order buy history`
@ba1ciu @gjermundgaraba Here I am just showing the error in the toast 😞,  I tried to catch the insufficient balance error, But there is no specific value to check that. Let me know if any way to fix the insufficient token balance issue.
> buy credit validation,show error message and UI fixes

- frontend/marketplace/src/components/BuyCredits.vue
- frontend/marketplace/src/components/NavBar.vue
1. Copy the wallet address
2. Reduced the buy credits input width
> copy wallet address and buy credits UI fix

- .github/workflows/chain_pre_release.yml
Sorry about the commit spam, but had to test it somehow 🤷🏻 And for commit messages - I was working on multiple branches simultaneously..
> Prerelease fix

- .github/workflows/chain_simulation_tests.yml
Consuming too much GH Action hours
> Turn off scheduled sim testing for empowerchain

- .github/workflows/frontend-marketplace-deploy-mainnet.yml
- .github/workflows/frontend-marketplace-deploy-testnet.yml
- .github/workflows/frontend-marketplace-deploy.yml
- frontend/marketplace/.env.prod
- frontend/marketplace/.env.test
- frontend/marketplace/package-lock.json
- frontend/marketplace/src/components/BuyCredits.vue
- frontend/marketplace/src/pages/AuctionDetails.vue
Small quality updates + test/prod deployment scripts
> Marketplace listing title update

- frontend/marketplace/src/pages/AuctionDetails.vue
> feat(marketplace): Update auction order history every 5 seconds

- frontend/marketplace/src/pages/CertificatePage.vue
- frontend/marketplace/src/pdfGenerator/pdfGenerator.ts
- frontend/marketplace/src/types/Credits.ts
- frontend/marketplace/src/types/index.d.ts
- frontend/marketplace/src/utils/utils.ts
This is #5837 but WITHOUT the QR code
> 5837 certificate adjustments

- frontend/marketplace/src/components/BuyButton.vue
- frontend/marketplace/src/components/BuyCredits.vue
- frontend/marketplace/src/components/NavBar.vue
- frontend/marketplace/src/stores/wallet.ts
Move address to a global state so we can let the buy button react to it when it changes.
Fixes https://github.com/EmpowerPlastic/empower-platform/issues/5705#issuecomment-1845160437
> fix(marketplace): Update buy button when connecting to a wallet

- frontend/marketplace/package-lock.json
- frontend/marketplace/package.json
- frontend/marketplace/src/components/BuyCredits.vue
** WARNING NOT TESTED **
This is a branch where we update the `contract.buyCredits` to include `retire`: true and `retiring_entity_name`
> fix(marketplace): Update to retire credits in one request

- frontend/marketplace/src/pages/AuctionDetails.vue
Issue: https://github.com/EmpowerPlastic/empower-platform/issues/6007
> fix(marketplace): Remove order history from auction page

- frontend/marketplace/src/components/CertificateTabContent.vue
Debugging stuff made it through to main. Let's remove it.
> chore(marketplace): Remove debugging

- frontend/marketplace/.env.development
- frontend/marketplace/src/pdfGenerator/pdfGenerator.ts
Issue: https://github.com/EmpowerPlastic/empower-platform/issues/5959
> feat(marketplace): Add who is issuer to cert and blockchain text

- frontend/marketplace/src/components/CertificateCard.vue
This will fix the QR codes on other environments than localhost and address first bullet here: https://github.com/EmpowerPlastic/empower-platform/issues/5837#issuecomment-1900092822
> fix(marketplace): Fix QR code on test and prod

- frontend/marketplace/src/utils/query-builder.ts
Issue - https://github.com/EmpowerPlastic/empower-platform/issues/6157
> changed query to check active amount

- frontend/marketplace/src/utils/query-builder.ts
Fix for https://github.com/EmpowerPlastic/empower-platform/issues/6157
> fix for showing zero listing

- frontend/marketplace/src/components/NavBar.vue
Fix for https://github.com/EmpowerPlastic/empower-platform/issues/6099
> Fix wallet and email login at the same time

- frontend/marketplace/src/components/CertificateCard.vue
- frontend/marketplace/src/components/NavBar.vue
- frontend/marketplace/src/pdfGenerator/pdfGenerator.ts
- frontend/marketplace/src/router/index.ts
- Hardcode QR url 
- Hide the user profile
> hardcode QR and hide user profile

- frontend/marketplace/src/router/index.ts
Issue - https://github.com/EmpowerPlastic/empower-platform/issues/6042
> added lazy load for router

- frontend/empowerjs/package-lock.json
- frontend/empowerjs/package.json
- frontend/empowerjs/src/plastic-credit-utils/empower-data-creator.ts
- frontend/empowerjs/test/empower-data.spec.ts
- indexer/schema.graphql
- indexer/src/mappings/mappingHandlers.ts
Long time since we revisited plastic credit index file and we definitely should have info about transaction type in there.
> Tracking event type

- frontend/marketplace/src/pages/AuctionPaymentSuccessful.vue
Issue - https://github.com/EmpowerPlastic/empower-platform/issues/6319
> purchase text change

- frontend/marketplace/src/components/AuctionResultsCard.vue
- frontend/marketplace/src/components/CustomImage.vue
- frontend/marketplace/src/components/ImageGallery.vue
Issue - https://github.com/EmpowerPlastic/empower-platform/issues/6320
> image stretch issue fix

- frontend/marketplace/src/components/FAQCollapse.vue
- frontend/marketplace/src/components/NavBar.vue
- frontend/marketplace/src/pages/FAQPage.vue
- frontend/marketplace/src/router/index.ts
Issue - https://github.com/EmpowerPlastic/empower-platform/issues/6318
> 6318 enable faq page

- frontend/marketplace/src/components/CertificateHolderModal.vue
Issue - https://github.com/EmpowerPlastic/empower-platform/issues/6367
> Certificate placeholder UI fix

- frontend/marketplace/src/components/ListingCard.vue
- frontend/marketplace/src/components/ListingCardTable.vue
- frontend/marketplace/src/utils/wallet-utils.ts
Issue - https://github.com/EmpowerPlastic/empower-platform/issues/6261
> use formatted denom in listing

- frontend/marketplace/src/components/CertificateCard.vue
- frontend/marketplace/src/utils/utils.ts
> IPFS image convert issue fix

- frontend/marketplace/src/components/BuyButton.vue
- frontend/marketplace/src/components/BuyCredits.vue
- frontend/marketplace/src/components/CertificateHolderModal.vue
- frontend/marketplace/src/types/CertificateHolderModalTypeEnums.ts
Issue - https://github.com/EmpowerPlastic/empower-platform/issues/6541
> buy credits without login
